### PR TITLE
1.4.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #67 - fix logging of events without a `State` or message template
 * #60 - update dependencies

### CODE REVIEW

**Comment by nblumhardt** [comment]
@merbla the update to MEL 1.1 could edge out some users still on 1.0, since upgrading drags forwards a whole bunch of other framework libraries. I'm still okay with this (we're not withdrawing the support already out there in 1.3.x of this lib) but now that we have bug fixes in this release I wonder whether going back to 1.0 (while keeping the updated Serilog dependency) might be a bit more accommodating. Thoughts?

**Comment by nblumhardt** [comment]
Attempting to back out the MEL dependency version bump isn't going so well - #69 - but I'd still rather support 1.0.0 if we can. Any ideas why that PR doesn't build?

**Comment by skomis-mm** [comment]
I think the problem is with [these](https://github.com/serilog/serilog-extensions-logging/pull/67/files#diff-b63d3f1419a8d455a029181f924348e0L25) lines for `net45(6)`. Reference to `System.Runtime` was unneeded for 1.1 since it was already referenced there so I removed them in that PR. 
So for backing up we need return these references or better put them in `frameworkAssemblies` section so they won't appear in `.nuspec`:
```json
"frameworkAssemblies": { "System.Runtime": { "type": "build" } }
```

**Comment by nblumhardt** [comment]
Thanks @skomis-mm 👍

**Pull request merged**
