### PR TITLE
Add more context information to SelfLog if log statement fails

### LINKED ISSUE #198: Provide more context information to SelfLog if a log statement fails
Consider [this](https://github.com/serilog/serilog-extensions-logging/blob/e25ed7ddfd0c664bd3a7e9cdbeeec6f87ff12964/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L69) line in the `SerilogLogger` implementation. 

As you can see there, if writing the log message fails, the exception is written to the SelfLog. This includes the exception stacktrace.
Unfortunately the stackrace of an exception only ever contains the stack frames between the point where the exception was thrown and the point where it is caught. Usually that is quite sufficient. But in the special case of structured logging the probability that the error was caused by an unsuitable input to the log statement is quite high. Regrettably that piece of information can not currently be gained from the message written to the SelfLog as the exception stacktrace ends when it is caught and written to the SelfLog.

A simple fix would be to manually append the current stacktrace to the message. Like so:
```
SelfLog.WriteLine($"Failed to write event through {typeof(SerilogLogger).Name}: {ex}\n{new System.Diagnostics.StackTrace()}");
```

If I recall correctly there have been other issues which request a more general way to improve the SelfLog capabilities but perhaps this   could be a

### PR DESCRIPTION
**Pull request by penenkel**
by appending the current stacktrace to the exception and its stacktrace.
Fixes #198

### CODE REVIEW

**Comment by chetankumar** [comment]
Can we please move this along? My team and I are desperately waiting on this.

**Comment by nblumhardt** [comment]
Hi @chetankumar! Try out the `SelfLog.Enable(m => ...)` callback; inside it, you can log the message (`m`) to wherever you like, and you can also write a `(new System.Diagnostics.StackTrace()).ToString()` there alongside it.

**Comment by sungam3r** [comment]
@nblumhardt close?

**Comment by nblumhardt** [comment]
👍 I think we're now discussing this and related issues over in serilog/serilog.

**Pull request closed without merging**
