### PR TITLE
Upgrade to dotnet CLI 1.0.3

### PR DESCRIPTION
**Pull request by adamchester**

### CODE REVIEW

**Comment by adamchester** [comment]
I don't understand the dotnet versioning at all, but the [latest](https://github.com/dotnet/cli/releases/latest) tag on [`dotnet/cli` repo](https://github.com/dotnet/cli) points to [1.0.3](https://github.com/dotnet/cli/releases/tag/v1.0.3) right now, and says:

> This is the release for the .NET Core SDK 1.0.3 with .NET Core 1.0.4 and .NET Core 1.1.1. The release was part of the April update for Visual Studio 2017 and includes <...>

I *suppose* that, where possible, we should try to use the latest 'point release' of the major version.

**Comment by nblumhardt** [comment]
Yep, sounds fair enough 👍

**Comment by adamchester** [comment]
This is ready to go

**Comment by nblumhardt** [comment]
Cool stuff!

That's me done for today; have a good Sunday, Adam :-)

**Comment by adamchester** [comment]
@nblumhardt thanks you too 👍

**Pull request merged**
