### PR TITLE
7.0.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #203 - observe `LogLevel.None` (@0xced)
 * #212 - eliminate some enumerator boxing (@sungam3r)
 * #210 - clean-up (@sungam3r)
 * #214 - migrate to .NET 7 and C# 11 (@sungam3r)
 * #216 - reduce allocations by caching trimmed `@` and `$` keys (@sungam3r)
 * #218 - fix exception handling in audit mode (@sungam3r)
 * #221 - add API approval tests (@sungam3r)
 * #222 - pin to `Microsoft.Extensions.Logging` v7 (@nblumhardt)

### CODE REVIEW

**Comment by nblumhardt** [comment]
This one's ready to go.

**Comment by sungam3r** [comment]
Wait for #219 ?

**Comment by nblumhardt** [comment]
Given the difficulty of getting everything into shape and out at the same time, I don't think we should hold up the release. There's always a 7.0.1, etc., to ship another day :-)

**Comment by niemyjski** [comment]
@nblumhardt why pin to v7 instead of lts v6?

**Comment by nblumhardt** [comment]
@niemyjski just practicalities, really. Hopefully most people who really need LTS versions of everything will already be managing dependency upgrades carefully and can stick with whatever they're using today. Otherwise, v7 of these packages all include .NET 6 targets anyway.

There's also a new LTS just around the corner with v8, we've already published a _Serilog.AspNetCore_ v6, and we don't want to have to coordinate shipping two new releases just to get the versioning policy bootstrapped. Did give it all lots of thought; always trade-offs whatever we do :-)

**Comment by sungam3r** [comment]
Do you intentionally not reference serilog v3 here and in other repos with such v7 releases?

**Comment by nblumhardt** [comment]
@sungam3r thanks for the double-check; yes, I think we still have some work to go on Serilog v3 👍 

I'm not sure at which stage we'll want to flip over the dependencies here (and in the other projects), if Serilog v3 is out within a few months, the v8 packages might pull it in, perhaps.

**Pull request merged**
