### PR TITLE
Make the level mapping routines public

### LINKED ISSUE #81: Make function ConvertLevel public availabe so we can use it in our code
Make function ConvertLevel public availabe so we can use it in our code

### PR DESCRIPTION
**Pull request by nblumhardt**
If there's any library where this belongs, I guess it's here. Resolves #81.

No tests, as they'd be pretty much an exact copy of the already-declarative code.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Any thoughts on this, @serilog/reviewers-core ?

**Comment by tsimbalar** [comment]
LGTM ! 👍 

I see it as extremely tempting to make them extension methods , but I suppose that YAGNI tells me that **NO** 🤷‍♂ 

(and if we were to do it, should the namespace be any different ? 🤔 )

**Comment by nblumhardt** [comment]
I thought about this, but came out on the side of restraint since usage will be very, very infrequent (as far as I can tell). Extension methods do bring all kinds of namespace pollution concerns into the picture :-) .. Might just side-step that and :shipit:

**Comment by nblumhardt** [comment]
Thanks for the review, BTW! :-)

**Comment by xrkolovos** [comment]
when will this feature be released?

**Comment by nblumhardt** [comment]
@xrkolovos thanks for the nudge; no plan yet, but https://github.com/serilog/serilog-extensions-logging/pull/145 is the PR to watch.

**Pull request merged**
