### PR TITLE
1.3.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #51 - support `@` operator in formatted scope messages
 * #55 - add hierarchical `Scope` property and capture more scope types including `"names"`

### CODE REVIEW

**Comment by cilerler** [comment]
Following code

```csharp
using (Logger.BeginScope("Some name"))
using (Logger.BeginScope(42))
using (Logger.BeginScope("Formatted {WithValue}", 12345))
using (Logger.BeginScope(new Dictionary<string, object> { ["ViaDictionary"] = 100 }))
```
ends up as 

image

and not like this

image

as stated in [here](https://github.com/serilog/serilog-extensions-logging/pull/55#issuecomment-260517005) for **Scope** item

**Comment by nblumhardt** [comment]
@cilerler thanks for checking it out. I've just installed the latest -pre:

```json
    "Serilog.Extensions.Logging": "1.3.0-dev-10129",
    "Serilog.Sinks.Seq": "3.1.1"
```

With the following in _Startup.cs_:

```csharp
            loggerFactory.AddSerilog(new LoggerConfiguration()
                .WriteTo.Seq("http://localhost:5341")
                .CreateLogger());
```

And the following in _HomeController.cs_:

```csharp
    public class HomeController : Controller
    {
        ILogger<HomeController> Logger;

        public HomeController(ILogger<HomeController> logger)
        {
            Logger = logger;
        }

        public IActionResult Index()
        {
            using (Logger.BeginScope("Some name"))
            using (Logger.BeginScope(42))
            using (Logger.BeginScope("Formatted {WithValue}", 12345))
            using (Logger.BeginScope(new Dictionary<string, object> { ["ViaDictionary"] = 100 }))
            {
                Logger.LogInformation("In");
            }

            return View();
        }
```

Result in Seq:

image

Can you spot any differences with the setup you're using?

**Comment by cilerler** [comment]
This is the first thing it looks different to me
instead of 
```
"Serilog.Extensions.Logging": "1.3.0-dev-10129",
"Serilog.Sinks.Seq": "3.1.1"
```

I have 

```
"Seq.Extensions.Logging": "2.1.0-dev-00022",
```

**Comment by nblumhardt** [comment]
Aha :-) that would be [this project](https://github.com/datalust/seq-extensions-logging).

If you change the version of the package to `2.1.1` you should get the output you're expecting.

Cheers!

**Comment by cilerler** [comment]
Sorry about that, changed it and confirming that it is working like a charm.  Thanks again! 😎

**Comment by merbla** [comment]
@nblumhardt  should we take to opportunity to bump to https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/1.1.0

**Comment by merbla** [comment]
And possibly v2.3.0 of Serilog?

**Comment by nblumhardt** [comment]
@merbla keen to push the version of the Serilog dependency forwards; I think it might be a bit early to cut off support for the 1.0 version of MEL, though - may be some apps that can't move forward yet.

Perhaps we bump both versions up in `dev` and do that in the next point release?

**Pull request merged**
