### PR TITLE
1.1.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
Includes:

 * #41 

(Plus build updates etc., since 1.0.0 was made off of the `dev` branch it would appear.)

### CODE REVIEW

**Comment by nblumhardt** [comment]
This one also. @merbla ?

**Comment by merbla** [comment]
Good just noting #40

**Comment by nblumhardt** [comment]
Didn't get packaged into the release, so left it out to avoid confusing anyone (it's not shipping code). What do you think? Happy to add it.

**Comment by merbla** [comment]
Makes sense, :shipit:

**Pull request merged**
