### PR TITLE
Build script for OSX/Nix & Samples update

### PR DESCRIPTION
**Pull request by merbla**
Follow on from #95.  Current example does not illustrate 2.0 release changes.

* Removed previous sample
* Added two new samples for vanilla web and WebAPI.

### CODE REVIEW

**Comment by merbla** [comment]
Not sure but we may want to include https://github.com/serilog/serilog-extensions-logging/blob/dev/samples/WebSample/appsettings.json in the samples.

**Comment by merbla** [comment]
These samples may need to be refined see https://github.com/aspnet/Logging/issues/670#issuecomment-324174361

**Comment by nblumhardt** [comment]
Looks good; updates can probably wait until we've dug deeper into the 2.0 issues. Ready to :shipit: ?

**Comment by merbla** [comment]
:shipit: This should provide a good playground for the issues in #98

**Pull request merged**
